// Función para ejecutar cualquier bloque dentro del contenedor Docker
def runInDocker(String image, Closure body) {
    docker.image(image).inside("-v ${pwd()}:/app -w /app") {
        withEnv(["PATH=/usr/share/maven/bin:$PATH"]) {
            body()
        }
    }
}


pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any
  // Parámetros del build para decidir si ejecutar CD
  parameters {
    booleanParam(name: 'RUN_CD', defaultValue: false, description: 'Ejecutar CD')
  }
  // Variables de entorno globales accesibles en todos los stages
  environment {
    IMAGE_NAME = "devops/ci:latest"
    APP_URL    = "http://localhost:8084/hello"
  }
  stages {
	// Stage 1: Construcción de la imagen CI
    stage('Build CI Image') {
      steps {
        sh 'docker build --build-arg VERSION=1.0.0 -t ${IMAGE_NAME} -f devops/ci.Dockerfile .'
      }
    }
	// Stage 2: Linter y formato de código
    stage('Lint') {
      steps {
        script {
          runInDocker('devops/ci:latest') {
            sh 'make lint'
          }
        }
      }
    }
	// Stage 3: Tests unitarios
    stage('Test') {
      steps {
        script {
          runInDocker('devops/ci:latest') {
            sh 'mvn test'
          }
        }
      }
    }
	// Stage 4: Despliegue simulado (CD)
    stage('CD') {
      when {
		// Ejecutar solo en develop/master o si RUN_CD=true
        anyOf {
          expression { return params.RUN_CD }
            branch 'develop'
            branch 'master'
          }
        }
      environment {
        // Variables dependientes de la rama
        DEPLOY_ENV = "${(env.BRANCH_NAME == 'master') ? 'PRO' : 'DEV'}"
        COMPOSE_PROJECT = "${(env.BRANCH_NAME == 'master') ? 'pro' : 'dev'}"		
      }
      steps {
        echo "CD habilitado: RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"
        echo "Deploying image: ${env.IMAGE_NAME}"
        echo "Application URL: ${env.APP_URL}"
        script {
          echo "Deploying to ${env.DEPLOY_ENV}"
          echo "RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"

          //def composeProject = (env.DEPLOY_ENV == 'PRO') ? 'pro' : 'dev'
          // Levanta los contenedores de la app usando Docker Compose
          sh "docker compose -p ${COMPOSE_PROJECT} up -d"
          sh "sleep 5"
          // sh "docker compose -p ${COMPOSE_PROJECT} logs app"          
		  sh "docker compose -p ${COMPOSE_PROJECT} up -d"
		  
		  // Espera hasta que la app responda
          sh """
          for i in {1..10}; do
            if curl -s ${env.APP_URL}; then
              echo "App is up!"
              break
            fi
            echo "Waiting for app to start..."
            sleep 2
          done
          """
	      
          // Comprobación final con curl
          sh "docker compose -p ${COMPOSE_PROJECT} exec -T app curl -f http://localhost:8080/hello"
        }
	  }	
	  // Hooks post del stage CD
      post {
        always {
          echo "Cleaning resources..."
          sh "docker compose -p ${COMPOSE_PROJECT} down --volumes || true"
          sh "docker rmi ${IMAGE_NAME} || true"
        }
        success {
          echo "SUCCESS"
        }
        failure {
          echo "FAILURE"
          sh "docker compose -p ${COMPOSE_PROJECT} logs || true"
        }
      }
    }
	// Stage 5: Info
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"

        echo "Imagen: ${env.IMAGE_NAME}"
        echo "URL App: ${env.APP_URL}"

        sh "echo IMAGE_NAME=${IMAGE_NAME}"
        sh "echo APP_URL=${APP_URL}"
      }
    }
  }// fin stages
}// fin pipeline
	
