/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/


// Función para ejecutar cualquier bloque dentro de un contenedor Docker
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Build CI Image') {
      steps {
        sh 'docker build --build-arg VERSION=1.0.0 -t devops/ci:latest -f devops/ci.Dockerfile .'
      }
    }
    stage('Lint') {
      steps {
        script {
          runInDocker('devops/ci:latest') {
            sh 'make lint'
          }
        }
      }
    }
    stage('Test') {      
      steps {
        script {
          runInDocker('devops/ci:latest') {
            sh 'mvn test'
          }
        }
      }
    }
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }
  }
}
