# Práctica 5 - Azure DevOps Pipelines 
# Ejercicio 1 - Estructura mínima
trigger: 
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Repository: $(Build.Repository.Name)"
    echo "Branch:     $(Build.SourceBranch)"
    echo "Commit:     $(Build.SourceVersion)"
  displayName: "Mostrar variables del build"
