# Práctica 5 - Azure DevOps Pipelines 
# Ejercicio 5 - CI por proyecto

trigger:
- develop
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI_Java
  displayName: "CI - Java (Maven)"

  container: maven:3.8.6-openjdk-11-slim

  steps:
  - checkout: self

  - script: |
      echo "Java version:"
      java -version
      echo "Maven version:"
      mvn -version
    displayName: "Check Java & Maven versions"

  - script: make lint
    displayName: "Compile Check (Lint)"

  - script: make test
    displayName: "Run Unit Tests"
