version: "3.7"

networks:
  java-project-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.234.0/24

# volumes:
  # postgresql-vol:
  # sonarqube-vol:

services:
  ## TO BUILD AND RUN APP LOCALLY
  app:
    #image: scalian_training-java-hello-world:0.0.2
    build: 
      context: .
      dockerfile: devops/Dockerfile
    container_name: java_app
    ports:
      - 8084:8080
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080

  # sonarqube:
  #   image: sonarqube:9.9.0-community
  #   depends_on:
  #     - sonardb
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #   volumes:
  #     - sonarqube-vol:/opt/sonarqube
  #   ports:
  #     - "9009:9000"
  #   hostname: sonarqube
  #   networks:
  #     java-project-net:
  #       ipv4_address: 172.16.234.10
  #       aliases: 
  #         - sonarqube

  # sonardb:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql
  #   hostname: sonardb
  #   networks:
  #     java-project-net:
  #       aliases: 

  #         - sonardb
